// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadingRoomStore.Models;

namespace ReadingRoomStore.Migrations
{
    [DbContext(typeof(ReadingRoomDBContext))]
    [Migration("20210202114931__test")]
    partial class _test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ReadingRoomStore.Models.Book", b =>
                {
                    b.Property<int>("BooksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BooKsMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BooksAouthers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BooksName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BooksPublishers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BooksId");

                    b.ToTable("books");
                });

            modelBuilder.Entity("ReadingRoomStore.Models.Donator", b =>
                {
                    b.Property<string>("DonatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DonatorPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonatorUserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DonatorId");

                    b.ToTable("Donators");
                });

            modelBuilder.Entity("ReadingRoomStore.Models.test", b =>
                {
                    b.Property<string>("testId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MyProperty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("testId");

                    b.ToTable("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
